Attendence/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name='app'
urlpatterns = [
    path('',views.home,name='Home'),
    path('<int:condidate_id>',views.home,name='Home'),
    path('login-user/',views.loginhand,name='Login'),
    path('logout-user/',views.logouthand,name='Logout'),
    path('create-user/<str:username>/<str:password>',views.createuser,name='Create Account'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
# Create your models here.

class Condidate(models.Model):
    user=models.ForeignKey(User, verbose_name="Condidate", on_delete=models.CASCADE)
    name=models.CharField("Condidate name", max_length=200)
    fname=models.CharField(("Father name"), max_length=200)
    pname=models.CharField(("Patient name"), max_length=200)
    serviceType=models.CharField("Service Type", max_length=200)
    Entrytime=models.TimeField("Entry Time", default=datetime.now)
    Exittime=models.TimeField("Exit Time", default=datetime.now)
    date=models.DateField(("Date"), auto_now=False, auto_now_add=False,default=datetime.today)
    
    def __str__(self) -> str:
        return self.user.username

app/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from .models import Condidate
from datetime import datetime
# Create your views here.


# ssss1234
def home(request,condidate_id=None):
    # return HttpResponse('Home page')
        
    if request.user.is_anonymous:
        return render(request,'app/login.html')
    elif condidate_id: 
        condidate=Condidate.objects.get(id=condidate_id)
        condidates=Condidate.objects.all()
        return render(request,'app/index.html',{'condidate':condidate,'Condidates':condidates})
    else:
        if request.method=="POST":
            name=request.POST.get('name')
            f_name=request.POST.get('fname')
            p_name=request.POST.get('pname')
            service_type=request.POST.get('service')
            if Condidate.objects.filter(user=request.user).exists():
                condidate=Condidate.objects.get(user=request.user)
                if condidate.Entrytime == condidate.Exittime:
                    Encondidate=Condidate.objects.get(user=request.user)
                    entryTime=Encondidate.Entrytime
                    Encondidate.delete()
                    condidate=Condidate(user=request.user,name=name,fname=f_name,pname=p_name,serviceType=service_type,Entrytime=entryTime)
                    condidate.save()
                    messages.success(request,'Exited !!')
                    # logout(request)
                    return HttpResponseRedirect(reverse("app:Home"))
                else:
                    messages.error(request,"You Aleready Exited !!")
                    return HttpResponseRedirect(reverse("app:Home"))

            else:
                condidate=Condidate(user=request.user,name=name,fname=f_name,pname=p_name,serviceType=service_type)
                condidate.save()
                messages.success(request,'Entered !!')
                return HttpResponseRedirect(reverse("app:Home",args=(condidate.id,)))
        else:
            condidates=Condidate.objects.all()
            return render(request,'app/index.html',{'Condidates':condidates})
    
def loginhand(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user_authenticated=authenticate(username=username,password=password)
        if user_authenticated:
            login(request,user_authenticated)
            messages.success(request,'Logged in successfully')
            return HttpResponseRedirect(reverse("app:Home"))
        else:
            messages.error(request,'Username or password is wrong')
            return render(request,'app/login.html')
    else:
        return render(request,'app/login.html')
def logouthand(request):
    logout(request)
    messages.success(request,"Successsfully logout !!")
    return redirect('/')

def createuser(request,username='',password=""):
    if (len(username)>1 and len(password)>1):
        if User.objects.filter(username=username).exists():
            messages.error(request,'Username is alerdy taken')
            return render(request,'app/login.html')
        else:
            user=User(username=username,password=password)
            user.save()
            login(request,user)
            messages.success(request,'User is created successfully !!')
            condidates=Condidate.objects.all()
            return render(request,'app/index.html',{'Condidates':condidates})
    else:
        messages.error(request,'Please enter username and password ')
        return render(request,'app/login.html')

templates/app/index.html
{% extends "base.html" %}

{% block title %}
Home page
{% endblock title %}


{% block body %}
<div class="container">
    <h1 class="mt-6 text-xl font-bold text-center">Home page {{user.username}}</h1>
    <div class="">
        <div class="form-box p-3 lg:w-[57%] mx-auto ">
            <h1 class="font-normal text-3xl mt-14 p-2">Attendence form</h1>
            <form action="{% url 'app:Home' %}" method="post" class="flex flex-col space-y-6 p-2">
                {% csrf_token %}
                <div class="flex flex-col space-y-1">
                    <label class="text-lg " for="name">Name</label>
                    <input type="text" placeholder="Your answer" id="name" name="name"
                        class="outline-none text-lg py-2 border-purple-200 caret-purple-600 border-b-2 focus:border-purple-600" required>
                </div>
                <div class="flex flex-col space-y-1">
                    <label class="text-lg " for="fname">Father Name</label>
                    <input type="text" placeholder="Your answer" id="fname" name="fname"
                        class="outline-none text-lg py-2 border-purple-200 caret-purple-600 border-b-2 focus:border-purple-600" required>
                </div>
                <div class="flex flex-col space-y-2">
                    <p class="text-lg font-normal">Service Type</p>

                    <label for="t_hr_day">
                        <input type="radio" id="t_hr_day" name="service" value="12 hr Day Shift" required>
                        12 hr Day shift</label>

                    <label for="t_hr_night">
                        <input type="radio" id="t_hr_night" name="service" value="12 hr Night Shift" required>
                        12 hr Night Shift</label>

                </div>
                <div class="flex flex-col space-y-1">
                    <label class="text-lg " for="pname">Patient Name</label>
                    <input type="text" name="pname" id="pname" placeholder="Your answer"
                        class="outline-none text-lg py-2 border-purple-200 caret-purple-600 border-b-2 focus:border-purple-600" value="" required>
                </div>
                <div class="">
                    <button type="submit" class="py-1 bg-purple-800 text-white rounded-xl px-4 font-normal text-lg">Submit</button>
                    <a role="button" href="{% url 'app:Logout' %}" class="py-1 bg-purple-800 text-white rounded-xl px-4 font-normal text-lg">Logout</a>

                </div>
            </form>
        </div>

        <div class="list mx-auto lg:w-1/2  mt-6 p-3">
            <p class="">All Condidates</p>
            <div class="py-4">
                {% for emp in Condidates  %}
                <ul class="flex justify-between mt-3">
                    <li class="">{{emp.name}}</li>
                    <li class="">{{emp.Entrytime}}</li>
                    <li class="">{{emp.Exittime}}</li>
                    <li class="">{{emp.date}}</li>
                </ul>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/app/login.html
{% extends "base.html" %}

{% block title %}
Login page
{% endblock title %}


{% block body %}
<div class="container">
    <div class="translate-y-[25%] ">
        <!-- <h1 class="text-center font-semibold lg:text-3xl text-lg">This is login  page</h1> -->
        <div class="login-form-box py-4 px-4 mx-auto lg:w-1/3">
            <div class="">
                <h1 class="text-3xl font-semibold text-center">Login 
                </h1>
                <!-- <p class="">Welcome !  </p>
                <p class="">Please login to continue</p> -->
            </div>
            <form action="{% url 'app:Login' %}" method="POST" class="mt-8 flex flex-col space-y-6">
                {% csrf_token %}
                <div class="flex flex-col space-y-1">
                    <label class="text-lg p-1" for="">Username</label>
                    <input class="text-lg p-2 outline focus:outline-purple-600 focus:outline-2 shadow-lg  caret-purple-950 outline-purple-500 outline-1 rounded" type="text" placeholder="Your username" id="username" name="username" required>
                </div>
                <div class="flex flex-col space-y-1">
                    <label class="text-lg p-1" for="">Password</label>
                    <input class="text-lg p-2 outline focus:outline-purple-600 focus:outline-2 shadow-lg   caret-purple-950 outline-purple-500 outline-1 rounded" type="password" placeholder="Your password" id="password" name="password" required >
                </div>
                <div class="">
                    <button class= "w-full bg-purple-950 text-white text-lg font-medium rounded-2xl p-2">LOGIN</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
create acount
{% endblock title %}


{% block body %}
<div class="container">
    <h1 class="text-center font-semibold text-3xl">This is sign up page</h1>
    <div class="login-form-box">
        <form action="">

        </form>
    </div>
</div>
{% endblock body %}

templates/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    
    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}
    <style>
    </style>
</head>

<body>
    {% for Message in messages %}
    <div id="alert" class="Dismissable-alert    p-2 bg-gray-100 w-full flex justify-between items-center">
        <p class=""><strong>{{Message.tags}} : </strong> {{Message}}</p>
        <span class="text-xl text-black px-2 rounded-lg  hover:bg-gray-300 active:text-white"
            id="dismiss_alert">&times;</span>
    </div>
    {% endfor %}
    {% block body %}

    {% endblock body %}
    
    <footer class="w-full h-32"></footer>
    {% block js %}
    {% endblock js %}
    <script>
        // Dissmiss Alert
        var alert = document.getElementById('alert');
        if (alert) {
            var alert_btn = document.getElementById('dismiss_alert');
            alert_btn.onclick = function () {
                var alert = document.getElementById('alert');
                if (alert.classList.contains('flex')) {
                    alert.classList.remove('flex');
                    alert.classList.add('hidden');
                }
            }
        }
    </script>

</body>

</html>